# Generated by Django 3.1 on 2021-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='client',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
