# Generated by Django 3.1 on 2021-06-24 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import questionnaire.models.survey_template


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210624_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Users can see it and answer it')),
                ('need_logged_user', models.BooleanField(verbose_name='Only authenticated users can see it and answer it')),
                ('editable_answers', models.BooleanField(default=True, verbose_name='Users can edit their answers afterwards')),
                ('display_method', models.SmallIntegerField(choices=[(1, 'By question'), (2, 'By category'), (0, 'All in one page')], default=0, verbose_name='Display method')),
                ('template', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template')),
                ('publish_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Publication date')),
                ('expire_date', models.DateField(blank=True, default=questionnaire.models.survey_template.in_duration_day, verbose_name='Expiration date')),
                ('client', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.surveytemplate', verbose_name='Survey'),
        ),
    ]
