# Generated by Django 3.1 on 2021-06-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210624_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveytemplate',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.survey', verbose_name='Survey'),
        ),
    ]
