# Generated by Django 3.1 on 2021-06-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20210624_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='survey_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questionnaire.surveytemplate', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questionnaire.survey', verbose_name='Survey'),
        ),
    ]
