# Generated by Django 3.1 on 2021-06-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20210624_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.surveytemplate'),
        ),
    ]
