# Generated by Django 3.1 on 2021-06-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20210625_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='title',
        ),
        migrations.AlterField(
            model_name='survey',
            name='client',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default=1, max_length=256, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
