# Generated by Django 3.1 on 2021-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20210625_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='display_method',
            field=models.SmallIntegerField(choices=[(1, 'By question'), (0, 'All in one page')], default=0, verbose_name='Display method'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='display_method',
            field=models.SmallIntegerField(choices=[(1, 'By question'), (0, 'All in one page')], default=0, verbose_name='Display method'),
        ),
    ]
