# Generated by Django 3.1 on 2021-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20210629_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
