# Generated by Django 3.1 on 2021-07-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20210707_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='question', max_length=256, null=True)),
                ('answer_this_part', models.TextField(blank=True, default='answer this part', max_length=1024, null=True)),
                ('button_next', models.TextField(blank=True, default='Next', max_length=64, null=True)),
                ('button_done', models.TextField(blank=True, default="I'm done!", max_length=64, null=True)),
                ('button_previous_page', models.TextField(blank=True, default='Previous page', max_length=64, null=True)),
                ('button_start_over', models.TextField(blank=True, default='Start over', max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='global_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.globaltext'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='global_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.globaltext'),
        ),
    ]
