# Generated by Django 3.1 on 2021-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20210709_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltext',
            name='answers_have_been_saved',
            field=models.TextField(blank=True, default='Thanks! Your answers have been saved', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='globaltext',
            name='survey_submitted',
            field=models.TextField(blank=True, default='Survey submitted', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='globaltext',
            name='you_can_change_answers',
            field=models.TextField(blank=True, default='You can always come back and change them.', max_length=256, null=True),
        ),
    ]
