# Generated by Django 3.1 on 2021-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_auto_20210709_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaltext',
            options={'verbose_name': 'global text', 'verbose_name_plural': 'global texts'},
        ),
        migrations.AddField(
            model_name='globaltext',
            name='name',
            field=models.TextField(default='Global text base', max_length=256),
            preserve_default=False,
        ),
    ]
