# Generated by Django 3.1 on 2021-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20210709_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('body', models.TextField(blank=True, default='question', max_length=256, null=True)),
                ('subject', models.TextField(blank=True, default='question', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'email text',
                'verbose_name_plural': 'email texts',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='email_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.emailtexts'),
        ),
    ]
