# Generated by Django 3.1 on 2021-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20210709_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtexts',
            name='body',
            field=models.TextField(blank=True, default='survey results', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='emailtexts',
            name='subject',
            field=models.TextField(blank=True, default='survey results', max_length=256, null=True),
        ),
    ]
