# Generated by Django 3.1 on 2021-07-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20210709_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTexts',
            new_name='EmailText',
        ),
    ]
