# Generated by Django 3.1 on 2021-07-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20210709_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('image', models.ImageField(default='bg1.jpg', upload_to='')),
                ('image_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'back ground image',
                'verbose_name_plural': 'back ground images',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.bgimage'),
        ),
    ]
