# Generated by Django 3.1 on 2021-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20210714_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgimage',
            options={'verbose_name': 'background image', 'verbose_name_plural': 'background images'},
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(default='bg1.jpg', upload_to='pics/'),
        ),
    ]
