# Generated by Django 3.1 on 2021-07-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20210714_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimage',
            name='image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='size: 700 x 800px'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.bgimage'),
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
