# Generated by Django 3.1 on 2021-07-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20210714_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='number_of_responses_per_page',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='background image site'),
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='background image pdf (size about: 700 x 800px)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.bgimage', verbose_name='background image'),
        ),
    ]
