# Generated by Django 3.1 on 2021-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0029_auto_20210614_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='nach_aufwand',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
