# Generated by Django 3.1 on 2021-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0030_auto_20210617_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='designation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
