# Generated by Django 3.1 on 2021-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0033_auto_20210617_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='nach_aufwand',
            field=models.BooleanField(default=False),
        ),
    ]
